package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/timzifer/blazon"
	"github.com/timzifer/blazon/blazontest"
)

// The gallery is generated, committed, and diffed. That makes it a visual
// regression test as much as documentation: if a refactor changes what the
// renderers draw, the change shows up as an image diff in the commit rather
// than going unnoticed.
const (
	galleryStartMarker = "<!-- gallery:start -->"
	galleryEndMarker   = "<!-- gallery:end -->"
)

// familyStrip is rendered for every renderer. It is the one picture that shows
// what the default policy actually does: three patches that stay in the
// family, a minor that varies it, and a major that starts over.
var familyStrip = []string{"1.0.0", "1.0.1", "1.0.2", "1.1.0", "2.0.0"}

func cmdGallery(args []string) error {
	fs := flag.NewFlagSet("gallery", flag.ContinueOnError)
	outDir := fs.String("o", filepath.Join("docs", "gallery"), "output directory")
	readme := fs.String("readme", "", "README file to rewrite between the gallery markers")
	corpusPath := fs.String("corpus", filepath.Join("testdata", "gallery.txt"), "gallery corpus")
	cell := fs.Int("cell", 96, "cell size in pixels")
	cols := fs.Int("grid", 6, "marks per contact sheet row")
	self := fs.String("self", blazon.Release, "version to draw the project's own logo from")
	if err := fs.Parse(args); err != nil {
		return err
	}

	// blazon's own mark for its own version. Regenerating it here rather than
	// checking in a hand-made logo keeps the project honest: the picture at
	// the top of the README is produced by the code underneath it.
	logo, err := blazon.SVG(*self, blazon.Options{Renderer: blazon.LogoRenderer, Size: 256})
	if err != nil {
		return fmt.Errorf("logo: %w", err)
	}
	if err := writeFile(filepath.Join(filepath.Dir(*outDir), "logo.svg"), logo); err != nil {
		return err
	}

	corpus, err := blazontest.LoadCorpus(*corpusPath)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		return err
	}

	names := blazon.Renderers()
	for _, name := range names {
		r, _ := blazon.Lookup(name)
		o := blazon.Options{Background: blazon.BackgroundLight}

		sheet, err := blazontest.ContactSheet(r, corpus, o, *cols, *cell)
		if err != nil {
			return fmt.Errorf("%s: contact sheet: %w", name, err)
		}
		data, err := blazon.EncodePNG(sheet)
		if err != nil {
			return err
		}
		if err := writeFile(filepath.Join(*outDir, name+"-sheet.png"), data); err != nil {
			return err
		}

		strip, err := blazontest.ContactSheet(r, familyStrip, o, len(familyStrip), *cell)
		if err != nil {
			return fmt.Errorf("%s: family strip: %w", name, err)
		}
		data, err = blazon.EncodePNG(strip)
		if err != nil {
			return err
		}
		if err := writeFile(filepath.Join(*outDir, name+"-family.png"), data); err != nil {
			return err
		}

		// One vector mark per renderer, so the README can show that the
		// output really is scalable and not only a bitmap.
		svg, err := blazon.SVG("1.4.2", blazon.Options{Renderer: name, Size: 256})
		if err != nil {
			return err
		}
		if err := writeFile(filepath.Join(*outDir, name+"-1.4.2.svg"), svg); err != nil {
			return err
		}
	}

	if *readme == "" {
		return nil
	}
	return rewriteReadme(*readme, *outDir, names)
}

// rewriteReadme replaces the section between the gallery markers. Plain marker
// substitution keeps the operation idempotent and dependency-free: running it
// twice must produce no diff, or the gallery job would commit on every push.
func rewriteReadme(path, outDir string, names []string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	text := string(raw)

	start := strings.Index(text, galleryStartMarker)
	end := strings.Index(text, galleryEndMarker)
	if start < 0 || end < 0 || end < start {
		return fmt.Errorf("%s: expected the markers %s and %s", path, galleryStartMarker, galleryEndMarker)
	}

	// Image links are written relative to the README, not to the working
	// directory, so the gallery renders correctly however the command was
	// invoked.
	rel, err := filepath.Rel(filepath.Dir(path), outDir)
	if err != nil {
		rel = outDir
	}
	rel = filepath.ToSlash(rel)

	var b strings.Builder
	b.WriteString(galleryStartMarker)
	b.WriteString("\n\n")
	b.WriteString("<!-- Generated by `blazon gallery`. Do not edit by hand. -->\n")
	for _, name := range names {
		r, _ := blazon.Lookup(name)
		b.WriteString("\n### " + name)
		if name == blazon.DefaultRenderer {
			b.WriteString(" (default)")
		}
		b.WriteString("\n\n")
		if caps := r.Caps(); caps.TextOnly {
			b.WriteString(fmt.Sprintf("Terminal renderer on a %d×%d character grid.\n\n",
				caps.GridCols, caps.GridRows))
		}
		b.WriteString(fmt.Sprintf("![%s across a version corpus](%s/%s-sheet.png)\n\n", name, rel, name))
		b.WriteString("Family: `1.0.0` → `1.0.1` → `1.0.2` → `1.1.0` → `2.0.0`\n\n")
		b.WriteString(fmt.Sprintf("![%s family strip](%s/%s-family.png)\n", name, rel, name))
	}
	b.WriteString("\n")
	b.WriteString(galleryEndMarker)

	updated := text[:start] + b.String() + text[end+len(galleryEndMarker):]
	if updated == text {
		return nil
	}
	return os.WriteFile(path, []byte(updated), 0o644)
}
